클럽 스키마 생성
Eriksen1212/nest-study-eventory pull request #3
Opened 2024-12-01 11:07 UTC by Eriksen1212

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [V] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
클럽 관련 스키마 생

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-12-01 11:19 UTC, worjs requested changes
다음에는 Reviewer로 넣어주세요!

그리고 User에서도 Club 모델 필드를 하나 추가해야할걸요..?
yarn prisma generate 먼저 해보실래요

2024-12-01 11:19 UTC, worjs commented on prisma/schema.prisma
> +}
1. enum은 대문자로 가실까요
2. 얘도 `@@map` 해주세요!
3. `거절됨` 상태는 필요 없을지도?

2024-12-01 11:19 UTC, worjs commented on prisma/schema.prisma
> +}
얘도 최대정원 넣읍시당

2024-12-01 11:19 UTC, worjs commented on prisma/schema.prisma
> +  joinState  String    @default("pending") // 가입 상태: "pending", "approved"
Enum을 만들었는데 타입은 그냥 String이예요!

2024-12-01 11:19 UTC, worjs commented on prisma/schema.prisma
> +  joinState  String    @default("pending") // 가입 상태: "pending", "approved"
얘는 `@map`안 되어 있네요

2024-12-01 11:19 UTC, worjs commented on prisma/schema.prisma
> +  createdAt  DateTime  @default(now()) @map("created_at")
updatedAt까지는 디폴트로 박고 가는걸로!

2024-12-01 11:19 UTC, worjs commented on prisma/schema.prisma
> +  members     ClubJoin[]  // 클럽 멤버
제 경험상 프리즈마에서 매핑테이블 모델링할때 이름 다르게 지으면 실제로 쓸때 좀 헷갈리더라구요

한번해보셔도 좋을듯
저는 저거 그냥 테이블 이름 따라서 지어요 `clubJoin ClubJoin[]`

2024-12-02 07:00 UTC, Eriksen1212 commented
피드백 반영해서 수정했습니다! yarn prisma generate은 지금 코드로는 에러 없이 돌아가는 것 같습니다. 확인 부탁드립니다.

2024-12-02 10:59 UTC, worjs requested changes

2024-12-02 10:59 UTC, worjs commented on prisma/schema.prisma
> +  clubId       Int?      @map("club_id") // (null 가능)
이거는 뭔가요?

2024-12-02 10:59 UTC, worjs commented on prisma/schema.prisma
> +}
1. RDB에서 enum의 이름은 테이블 이름과 똑같이 snake_case로 가는게 관례입니다.
2. TS에서 enum의 이름은 클래스 이름과 동일하게 PascalCase가 관례입니다.
3. RDB에서 enum의 값은 주로 snake_case, 가끔 TS와 일관성을 맞추기 위해 UPPER_CASE를 쓰기도 합니다.
4. TS에서 enum의 값은 주로 UPPER_CASE를 쓰는게 관례입니다.

네이밍에 있어서 관례를 따르는건 읽기와 유지보수를 쉽게 만든다는 점에서 협업할 때 굉장히 중요한 부분이기에, 한번만 더 수정 부탁드립니다~~

2024-12-02 10:59 UTC, worjs commented on prisma/schema.prisma
> +}
`@@map `사용하면 enum의 제목도 바꿀 수 있습니다!

2024-12-02 10:59 UTC, worjs commented on prisma/schema.prisma
> +  ownerId     Int         @unique @map("owner_id") // 클럽장
ownerId를 unique하게 설정하셨군요?
그러면 ownerId만 가지고 club을 조회할 수 있게 됩니다.
즉, 유저(owner)와 club이 일대일 대응 관계가 됩니다.

유저는 반드시 한개의 클럽만 생성할 수 있다는 요구사항은 없었으니 해당 조건은 빼는게 맞겠습니다.

2024-12-02 15:29 UTC, Eriksen1212 commented
User 부분에서 clubid 없애서 수정하고 owner_id에서 unique는 제거했습니다.
enum JoinState로 이름 변경하고 @@map("join_state")로 제목도 바꿨습니다.
감사합니당

2024-12-02 16:14 UTC, worjs commented
`@@Map("join_state")`
요고는 안바뀐거 같은데요?

저거만 반영해서 Migration하고 머지하시죠!

2024-12-03 08:19 UTC, Eriksen1212 commented
방금 @@Map("join_state")   저장해서 다시 커밋하고 migration까지 진행했습니다! 머지까지 하겠습니다.

2024-12-03 08:50 UTC, worjs commented
넵 고고고고고

2024-12-03 09:53 UTC, merged